version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-template
    ports:
      - "3000:3000"
    networks:
      - coolify
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

networks:
  coolify:
    external: true
